development:
  encoding: unicode
  adapter: postgresql
  database: tiendatadb_development
  pool: 5
  timeout: 5000
  username: postgres
  password: lamberto
  host: localhost
  port: 5432 

test:
  encoding: unicode  
  adapter: postgresql
  database: tiendatadb_test
  pool: 5
  timeout: 5000
  username: postgres
  password: lamberto
  host: localhost
  port: 5432

production:
  encoding: unicode
  adapter: postgresql
  database: tiendatadb_production
  pool: 5
  timeout: 5000
  username: postgres
  password: lamberto
  host: localhost
  port: 5432
